import React from 'react';
import { AIAnalysisResult } from '../types';
import { TrendingUp, TrendingDown, AlertTriangle, ShieldCheck, Activity } from 'lucide-react';

interface AnalysisPanelProps {
  analysis: AIAnalysisResult | null;
  isLoading: boolean;
  symbol: string;
}

const AnalysisPanel: React.FC<AnalysisPanelProps> = ({ analysis, isLoading, symbol }) => {
  if (isLoading) {
    return (
      <div className="w-full p-8 bg-slate-900 rounded-xl border border-slate-700 animate-pulse flex flex-col items-center justify-center h-full min-h-[400px]">
        <Activity className="w-12 h-12 text-blue-500 mb-4 animate-spin" />
        <p className="text-slate-400">Odoc AI is analyzing market data for {symbol}...</p>
        <p className="text-slate-500 text-sm mt-2">Processing fundamentals, technicals, and sentiment.</p>
      </div>
    );
  }

  if (!analysis) {
    return (
      <div className="w-full p-8 bg-slate-900 rounded-xl border border-slate-700 h-full min-h-[400px] flex items-center justify-center text-slate-500">
        Enter a symbol and click Analyze to generate a report.
      </div>
    );
  }

  const getRecColor = (rec: string) => {
    switch (rec) {
      case 'Buy': return 'text-green-400 border-green-900 bg-green-900/20';
      case 'Sell': return 'text-red-400 border-red-900 bg-red-900/20';
      default: return 'text-yellow-400 border-yellow-900 bg-yellow-900/20';
    }
  };

  return (
    <div className="w-full bg-slate-900 rounded-xl border border-slate-700 overflow-hidden shadow-lg flex flex-col h-full">
      <div className="bg-slate-800 p-4 border-b border-slate-700 flex justify-between items-center">
        <h3 className="text-lg font-bold text-white flex items-center gap-2">
          <ShieldCheck className="w-5 h-5 text-blue-400" />
          AI Analyst Report: {symbol}
        </h3>
        <span className={`px-3 py-1 rounded-full text-sm font-bold border ${getRecColor(analysis.recommendation)}`}>
          {analysis.recommendation.toUpperCase()}
        </span>
      </div>

      <div className="p-6 space-y-6 overflow-y-auto custom-scrollbar">
        {/* Summary */}
        <div>
          <h4 className="text-slate-400 text-xs font-uppercase tracking-wider mb-2">EXECUTIVE SUMMARY</h4>
          <p className="text-slate-200 leading-relaxed text-sm">{analysis.summary}</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {/* Bull Case */}
          <div className="bg-slate-950/50 p-4 rounded-lg border border-slate-800">
            <h4 className="text-green-400 text-sm font-bold mb-2 flex items-center gap-2">
              <TrendingUp className="w-4 h-4" /> Bullish Thesis
            </h4>
            <p className="text-slate-300 text-xs leading-relaxed">{analysis.bullishCase}</p>
          </div>

          {/* Bear Case */}
          <div className="bg-slate-950/50 p-4 rounded-lg border border-slate-800">
            <h4 className="text-red-400 text-sm font-bold mb-2 flex items-center gap-2">
              <TrendingDown className="w-4 h-4" /> Bearish Thesis
            </h4>
            <p className="text-slate-300 text-xs leading-relaxed">{analysis.bearishCase}</p>
          </div>
        </div>

        {/* Risks */}
        <div>
          <h4 className="text-orange-400 text-sm font-bold mb-2 flex items-center gap-2">
            <AlertTriangle className="w-4 h-4" /> Key Risks
          </h4>
          <ul className="list-disc list-inside space-y-1">
            {analysis.keyRisks.map((risk, idx) => (
              <li key={idx} className="text-slate-300 text-xs">{risk}</li>
            ))}
          </ul>
        </div>
        
        <div className="pt-4 border-t border-slate-800">
             <p className="text-[10px] text-slate-600 italic">
                Disclaimer: This analysis is generated by AI (Gemini) and does not constitute financial advice. Always verify with official sources.
            </p>
        </div>
      </div>
    </div>
  );
};

export default AnalysisPanel;